apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: loonar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-configmap
  namespace: loonar
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Nginx NodePort Deployment</title>
    </head>
    <body>
        <h1>Welcome to Nginx NodePort Deployment!</h1>
    </body>
    </html>